#=============================================================================
# File Name    : Makefile
# Revision History
#---------------------------------------------------------------------------
# Date       Author      	Version     Description
#---------------------------------------------------------------------------
#============================================================================

run :
	python ann_mnist.py -infile define.txt


clean :
	rm -f  weights_*
	rm -f  biases_*
	rm -f  all*
	rm -f  layer_outputs*
	rm -f  *.csv
	rm -f  *.h